### ISSUE TITLE
spiff diff does not show differences in template ordering

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry-incubator/spiff#75] opened 2016-06-06 09:01 UTC
spiff diff fails to recognize that the ordering of templates is relevant (not for bosh but -in practice- for monit)
```
$ cat a.yml 
---
templates:
  mytemplate:
  - name: A
    version: 1
  - name: B
    version: 2
$ cat b.yml 
---
templates:
  mytemplate:
  - name: B
    version: 2
  - name: A
    version: 1
$ spiff diff a.yml b.yml 
no differences!
$ spiff -v
spiff version 1.0.8dev
```

**Comment by Amit-PivotalLabs** [comment] 2016-06-07 04:02
I was able to reproduce this issue off the latest official release of `spiff`.  Since only severe issues are being fixed in `spiff` at this time, we will document this as a known issue in the `README` on the `master` branch.

**Comment by dsabeti** [comment] 2016-06-08 18:06
The README changes have been made: https://github.com/cloudfoundry-incubator/spiff/commit/1d3169748936e4891a4f6f6d082e6d0537abaca3

**Closed** 2016-06-08 18:08 UTC
Labels: delivered

**Comment by Amit-PivotalLabs** [comment] 2016-06-12 02:42
@CAFxX turns out this is actually intentional.  `spiff diff` only notifies you of changes that matter for a deployment manifest, so if you're using it to diff arbitrary YAML you might not get expected results.  I've updated the README.

As you point out, BOSH doesn't technically guarantee anything about the ordering of templates (https://github.com/cloudfoundry/bosh/issues/832) so it makes sense that spiff doesn't tell you anything about those diffs.  Perhaps in practice it matters, but I'm not sure spiff should have knowledge of undocumented behaviour in BOSH.  Given that spiff isn't under active development, I'm not inclined to actually change any spiff code.
